device: 1

# Dataset
path_to_excel: "modality_data_split801010.xlsx"
modality_1: "T1_FS_KM"
modality_2: "T2"
modality_1_label: T1_label
modality_2_label: T2_label

# Data Processing
h: 512
w: 512
depth: 32

# Optimization
batch_size: 4
num_workers: 4
input_channels: 1
nConv: 2
nChannel: 30
lr: 0.001
num_epochs: 700
patience: 10

# Label generation
lab_generation_split: "VAL"
